spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_renting
    username: root
    password: root
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.mysql5dialect
